use crate::errors::CliError;
use crate::git;
use crate::output::format::OutputFormat;
use dialoguer::{Input, Select};
use std::fs;

pub fn run(json: bool) -> Result<(), CliError> {
    let format = OutputFormat::detect(json);

    if !git::is_git_repo() {
        return Err(CliError::NotGitRepo);
    }

    if std::path::Path::new("autoresearch.toml").exists() {
        match format {
            OutputFormat::Json => {
                println!(
                    "{}",
                    serde_json::json!({"status": "already_initialized", "message": "autoresearch.toml already exists"})
                );
            }
            OutputFormat::Table => {
                println!("autoresearch.toml already exists. Edit it directly to change settings.");
            }
        }
        return Ok(());
    }

    // Interactive setup
    let target_file: String = Input::new()
        .with_prompt("Target file (the single file the agent may modify)")
        .interact_text()
        .map_err(|e| CliError::Config(e.to_string()))?;

    let eval_command: String = Input::new()
        .with_prompt("Eval command (produces the metric)")
        .interact_text()
        .map_err(|e| CliError::Config(e.to_string()))?;

    let metric_name: String = Input::new()
        .with_prompt("Metric name (e.g., val_bpb, accuracy, p99_latency)")
        .default("metric".to_string())
        .interact_text()
        .map_err(|e| CliError::Config(e.to_string()))?;

    let directions = &["lower is better", "higher is better"];
    let direction_idx = Select::new()
        .with_prompt("Metric direction")
        .items(directions)
        .default(0)
        .interact()
        .map_err(|e| CliError::Config(e.to_string()))?;
    let metric_direction = if direction_idx == 0 {
        "lower"
    } else {
        "higher"
    };

    let time_budget: String = Input::new()
        .with_prompt("Time budget per experiment (e.g., 5m, 30s, 1h)")
        .default("5m".to_string())
        .interact_text()
        .map_err(|e| CliError::Config(e.to_string()))?;

    let branch: String = Input::new()
        .with_prompt("Experiment branch name")
        .default("autoresearch".to_string())
        .interact_text()
        .map_err(|e| CliError::Config(e.to_string()))?;

    // Write autoresearch.toml
    let config = format!(
        r#"# Autoresearch configuration
# Generated by autoresearch CLI v{version}

# The single file the agent is allowed to modify
target_file = "{target_file}"

# Command that produces the metric (must print the metric value to stdout)
eval_command = "{eval_command}"

# Name of the metric being optimized
metric_name = "{metric_name}"

# Direction: "lower" or "higher"
metric_direction = "{metric_direction}"

# Maximum time per experiment run
time_budget = "{time_budget}"

# Git branch for experiments
branch = "{branch}"
"#,
        version = env!("CARGO_PKG_VERSION"),
    );

    fs::write("autoresearch.toml", &config)?;

    // Create .autoresearch directory
    fs::create_dir_all(".autoresearch")?;

    // Create program.md if it doesn't exist
    if !std::path::Path::new("program.md").exists() {
        let program = format!(
            r#"# Autoresearch Program

## Goal
Optimize `{metric_name}` ({metric_direction} is better) by modifying `{target_file}`.

## Ideas to Explore
<!-- Add your research directions, ideas, and hypotheses here.
     The agent will read this file for inspiration between experiments. -->

1.

## Constraints
- Time budget per experiment: {time_budget}
- Only modify: {target_file}
- Eval command: `{eval_command}`

## Notes
<!-- Add observations, links to papers, or domain knowledge here -->
"#,
        );
        fs::write("program.md", &program)?;
    }

    match format {
        OutputFormat::Json => {
            println!(
                "{}",
                serde_json::json!({
                    "status": "success",
                    "files_created": ["autoresearch.toml", "program.md", ".autoresearch/"],
                    "config": {
                        "target_file": target_file,
                        "eval_command": eval_command,
                        "metric_name": metric_name,
                        "metric_direction": metric_direction,
                        "time_budget": time_budget,
                        "branch": branch,
                    }
                })
            );
        }
        OutputFormat::Table => {
            println!();
            println!("Initialized autoresearch project:");
            println!("  autoresearch.toml  — experiment configuration");
            println!("  program.md         — research direction & ideas (edit this!)");
            println!("  .autoresearch/     — experiment logs");
            println!();
            println!(
                "Next: edit program.md with your ideas, then tell your agent to run /autoresearch"
            );
        }
    }

    Ok(())
}
